services:
  terminal:
    build: .
    container_name: terminal
    restart: unless-stopped
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 200s
      timeout: 200s
      retries: 5
